project:
  type: website
  output-dir: docs

website:
  title: "A bit of probability"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      
format:
  html:
    theme: cosmo
    page-layout: full
    css: styles.css

editor: source


